syntax = "proto3";

package ipi;

// ============================================================
// Policial (Login / Autenticação)
// ============================================================
message Policial {
    string id = 1;
    string matricula = 2;
    string nome = 3;
    string senha_hash = 4;
    string criada_em = 5;
}

// ============================================================
// Registro de Atendimento Integrado (RAI) / Ocorrência
// ============================================================
message RAI {
    string id = 1;
    string data_hora = 2;
    string matricula_operador = 3;
    string tipo = 4;
    string descricao = 5;
    Localizacao localizacao = 6;
    repeated Pessoa pessoas = 7;
    repeated Veiculo veiculos = 8;
    bool sincronizado = 9;
    string municipio = 10; // Município da operação/missão
}

// ============================================================
// Localização
// ============================================================
message Localizacao {
    double latitude = 1;
    double longitude = 2;
    string referencia_endereco = 3;
}

// ============================================================
// Pessoa
// ============================================================
message Pessoa {
    string cpf = 1;
    string nome = 2;
    string data_nascimento = 3;
    string tipo_mandado = 4;
    string observacao = 5;
    string situacao = 6; // REGULAR, MANDADO_PRISAO, FICHA_CRIMINAL
    string envolvimento = 7; // Suspeito, Vítima, Testemunha, Autor
    string municipio = 8;
}

// ============================================================
// Veículo
// ============================================================
message Veiculo {
    string placa = 1;
    string modelo = 2;
    string cor = 3;
    string ano_fabricacao = 4;
    string proprietario = 5;
    string numero_boletim = 6;
    string situacao = 7; // REGULAR, ROUBADO, FURTADO, QUEIXADO
    string municipio = 8;
}

// ============================================================
// Consulta
// ============================================================
message Consulta {
    string id = 1;
    string tipo_consulta = 2; // PESSOA, VEICULO
    string parametros = 3; // Placa ou CPF
}
